### PR TITLE
WL-4107: Use font awesome in citations

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by buckett** [comment]
In Sakai trunk this probably want to be loaded from /library. Is it better for us to have it in /sakai-citation-tool?

**Comment by nicholaswilson100** [comment]
Linked to  https://github.com/ox-it/wl-sirlouie/pull/9 and https://github.com/ox-it/wl-reference/pull/110

**Comment by nicholaswilson100** [comment]
I wasn't sure. I was half way between thinking it needed to be in reference and thinking only citations uses it at the moment... what do you think? I guess reference is the way to go...

**Comment by buckett** [comment]
In Sakai it should use /library.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
ok.  

also, unrelated, how do we do our library versioning? I was going to put it in a folder called  font-awesome (rather than font-awesome-4.4.0 as it currently is) as it makes it easier to update.  But you can easily see the version with the version there. But we do different things in different places I see.

**Comment by buckett** [comment]
The plan for Sakai is to use webjars (webjars.org) but this hasn't quite
happened yet. This gives you nice versioned URLs.

## 

  Matthew Buckett, VLE Developer, IT Services, University of Oxford

**Comment by nicholaswilson100** [comment]
Removed font awesome

**Pull request merged**
