### PR TITLE
WL-3848 : fix problems with citations that arent present in Sakai

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Because the fixes are small, I fixed them myself rather than trying to work out what to cherry-pick (which was taking ages).

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
I've removed the order.clear() line because it was causing the order of a citation to be removed even if it had been changed. This fixes 1/.

For 2/, all was happening was that the vm was feeding through resourceId rather than contentCollectionId so we were getting a 403 when unlock() was called with a null resource.

**Comment by buckett** [comment]
If these are bugs with features we've implemented we need to know which features are broken so that when we send patches back we don't introduce the same bugs in Sakai, and if they are fixes that are present in Sakai that we don't have on our 10.x branch we need to make sure that we fix them in the same way otherwise when we try to merge them back we will attempt to fix a problem that doesn't exist.

**Comment by nicholaswilson100** [comment]
Ok I've commented on the Jira and linked the relevant one.

**Comment by buckett** [comment]
Looking at WL-3848 I'm not sure which issue introduced the bugs that this fix needs.

**Comment by nicholaswilson100** [comment]
Also linked to this Jira:
https://jira.oucs.ox.ac.uk/jira/browse/WL-3843

**Comment by buckett** [comment]
But there is more than one Jira issue and only one commit here, if I'm merging back how would I know which bit of this commit relates to which issue?

**Pull request closed without merging**
