### PR TITLE
WL-3956: Add placeholder book image when no image in json or bad url

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Ceri from SSL is hopefully giving us a new image this or next week to use but Adam wants something for now so that if we release it looks okay.

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
PNG is from https://pixabay.com/en/book-cover-education-layout-page-307045/

**Comment by buckett** [comment]
Isn't it better to put the placeholder in the HTML so you don't have to wait for the JS to run and fail to find a book?

**Comment by nicholaswilson100** [comment]
but then a user with a slow connection sees the placeholder image and then the actual book cover?

**Comment by buckett** [comment]
But isn't it pretty much always the case that there will be items in the list without a cover so you'll end up loading anyway. Loading a static image is fast and should be cached well it just hurts the first time.

**Comment by nicholaswilson100** [comment]
that's true  .. ok

**Comment by buckett** [comment]
If you're wanting to improve slow connection performance resizing the image to the size that it will be used at will improve things.

**Comment by nicholaswilson100** [comment]
Yup I'll do that when I get the image form Ceri. Other than resizing, there are also tools to do lossless compression.

**Comment by nicholaswilson100** [comment]
In HTML now and rebased

**Comment by buckett** [comment]
Doesn't merge cleanly.

**Comment by nicholaswilson100** [comment]
ok rebased it

**Pull request merged**
