### PR TITLE
adding_cit_col_order_column_names: there only seem to be 2 places

### PR DESCRIPTION
**Pull request by nicholaswilson100**
where this happens

### CODE REVIEW

**Comment by buckett** [comment]
Could you just put a Jira reference on the commit.

**Comment by nicholaswilson100** [comment]
a reference or a new Jira?

**Comment by buckett** [comment]
There's a `select *` on line 908

**Comment by nicholaswilson100** [comment]
https://jira.oucs.ox.ac.uk/jira/browse/WL-3961

This code is meant to support running the SQL in this Jira as a migration script after the 4th release that will add 2 columns to CITATION_COLLECTION_ORDER.

**Comment by nicholaswilson100** [comment]
I've tested this code against the current DB and then after running the migration script which adds 2 columns

**Comment by buckett** [comment]
Could you just rebase and put the jira reference on the commits and I'll merge.

**Comment by nicholaswilson100** [comment]
ok. done.

**Pull request merged**
