### PR TITLE
WL-3978: Check first if google books function is defined

### PR DESCRIPTION
**Pull request by nicholaswilson100**

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
I forgot citations.js is also present on the edit reading list screen where our google books jquery pluginis not defined so it throws a js error.  There doesn't seem to be any js specific to the view reading list screen. I could have created one but this check to see if the function exists is neater/ and cleaner.

**Comment by buckett** [comment]
I don't think it's worth pull requests for tiny things like this when you're going to be doing work in this area anyway. Just include it in something else as a separate commit.

**Comment by nicholaswilson100** [comment]
ok

**Comment by buckett** [comment]
It's also best to put that really useful paragraph in the git commit, rather than as a pull request comment as it's much easier to find in 6 months time.

**Comment by buckett** [comment]
Or just put it on the pull request that introduced this problem as it's not yet released to you can re-open the original issue.

**Pull request merged**
